# Campus-specific variables
multi_auth = false
campus_code = "cc"
campus_name = "The City College of New York"
library_url = "https://library.ccny.cuny.edu/"
catalog_url = "https://cuny-cc.primo.exlibrisgroup.com/discovery/search?vid=01CUNY_CC:CUNY_CC"
db_url = "hhttp://library.ccny.cuny.edu/az.php"
ill_url = "https://library.ccny.cuny.edu/services/ILL"
ask_url = "https://library.ccny.cuny.edu/askus"
helpdesk_url = "https://cunyithelp.cuny.edu/csp?id=cuny_kb_article&sys_id=df83af0fdb812850ca2afdbaf49619ae"
library_help = ""
