name: Push Main

on:

  push:
    branches:
      - main

jobs:

  build_sites:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install jinja2

    - name: Build
      run: python build.py

    - uses: actions/upload-artifact@v4
      with:
        name: output
        path: output/
