name: Push Main

on:

  push:
    branches:
      - main

jobs:

  build_sites:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - uses: workflow/nix-shell-action@v3.3.0
      with:
        flakes-from-devshell: true
        script: |
          cargo install --git https://github.com/chevdor/tera-cli --tag v0.3.0 --root .
          bash build.sh
